apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service
          image: bank-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/bank_db
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka/
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank-service
  ports:
    - port: 8082
      targetPort: 8082
