spring.application.name=partner-service


#spring.application.name=Partner-Service
#
#server.port=8081
#
## ===========================
## PostgreSQL Configuration
## ===========================
#spring.datasource.url=jdbc:postgresql://localhost:5433/partner_db?options=-c%20TimeZone=Asia/Kolkata
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## ===========================
## JPA / Hibernate
## ===========================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
## ===========================
## Eureka Client
## ===========================
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## Optional
#eureka.instance.prefer-ip-address=true
#
## ===========================
## Feign Client
## ===========================
#spring.cloud.openfeign.client.config.default.connectTimeout=5000
#spring.cloud.openfeign.client.config.default.readTimeout=5000
#
## ===========================
## Resilience4j Circuit Breaker
## ===========================
#resilience4j.circuitbreaker.instances.bankService.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.bankService.minimum-number-of-calls=5
#resilience4j.circuitbreaker.instances.bankService.sliding-window-size=5
#resilience4j.circuitbreaker.instances.bankService.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.bankService.permitted-number-of-calls-in-half-open-state=2
#
## Retry Configuration
#
#resilience4j.retry.instances.bankService.max-attempts=3
#resilience4j.retry.instances.bankService.wait-duration=2s
#logging.level.io.github.resilience4j.retry=DEBUG
#logging.level.org.springframework.cloud.openfeign=DEBUG
#
#resilience4j.ratelimiter.instances.bankService.limit-for-period=2
#resilience4j.ratelimiter.instances.bankService.limit-refresh-period=10s
#resilience4j.ratelimiter.instances.bankService.timeout-duration=0
#
## ===========================
## Actuator
## ===========================
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#
## Optional
#logging.level.org.springframework.web=DEBUG
